=== moritzruth/among-us-mod-manager/resources/mods.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["id", "title", "author", "downloadURL", "projectURL", "version", "minManagerVersion", "amongUsVersion"],
    "additionalProperties": false,
    "properties": {
      "id": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "author": {
        "type": "string"
      },
      "downloadURL": {
        "type": "string"
      },
      "projectURL": {
        "type": "string"
      },
      "version": {
        "type": "string"
      },
      "minManagerVersion": {
        "type": "string"
      },
      "amongUsVersion": {
        "type": "string"
      }
    }
  }
}

=== moritzruth/among-us-mod-manager/resources/mods.json
[
  {
    "id": "the-other-roles",
    "title": "The Other Roles",
    "author": "Eisbison",
    "downloadURL": "https://github.com/Eisbison/TheOtherRoles/releases/download/v3.4.3/TheOtherRoles.zip",
    "version": "3.4.3",
    "projectURL": "https://github.com/Eisbison/TheOtherRoles",
    "minManagerVersion": "1.3.0",
    "amongUsVersion": "2021.12.15"
  },
  {
    "id": "town-of-impostors",
    "title": "Town of Impostors",
    "author": "AJMix",
    "downloadURL": "https://github.com/Town-of-Impostors/TownOfImpostors/releases/download/v2.0.8/TownOfImpostors2.0.8.zip",
    "version": "2.0.8",
    "projectURL": "https://github.com/Town-of-Impostors/TownOfImpostors",
    "minManagerVersion": "1.3.0",
    "amongUsVersion": "2021.6.15"
  }
]
